import com.backend.admin.model.Log;

rule "Error log"
agenda-group "logs"
    when
        $log : Log(level.equals("ERROR"))
    then
        System.out.println("NEW ERROR LOG DETECTED: " + $log.getMessage());
        //TODO: notification?
end

rule "Too many failed logins"
agenda-group "logs"
    when
        $log : Log(message.contains("Too many failed login attempts. Blocking user: "))
    then
        System.out.println("THREE OR MORE FAILED LOGINS DETECTED: " + $log.getMessage());
        //TODO: notification?
end